; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit MLX90614 Library @ ^2.1.5
    adafruit/Adafruit Unified Sensor @ ^1.1.14
extra_scripts = pre:read_env.py

[env:gateway]
extends = env:nanoatmega328
build_src_filter = +<gateway/>

[env:full_node]
extends = env:nanoatmega328
build_src_filter = +<full_node/>

[env:light_node]
extends = env:nanoatmega328
build_src_filter = +<light_node/>

[env:thermal_fence]
extends = env:nanoatmega328
build_src_filter = +<thermal_fence/>
